### ISSUE TITLE
Prototipo 

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-dream-team1-0#1]
[Prototipo .pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-dream-team1-0/files/10843323/Prototipo.pdf)

**Comment by bg55-a** [comment]
Calificacion: 20

**Comment by josealfredo79** [comment]
Bien hecho
